In [39]:
import pandas as pd

In [40]:
df = pd.read_csv("collision_crash_2020_2024.csv")

In [41]:
df.shape

(36303, 231)

In [42]:
df.head()

,X,Y,objectid,crn,arrival_tm,automobile_count,belted_death_count,belted_susp_serious_inj_count,bicycle_count,bicycle_death_count,...,unlicensed,unsignalized_int,urban,vehicle_failure,vehicle_towed,vulnerable_road_user,vulnerable_road_user_fatal,wet_road,work_zone,young_driver
0,-8.376536e+06,4.860532e+06,1,2020007295,NaN,4,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
1,-8.379867e+06,4.862518e+06,2,2020066105,1742.0,1,0,0,0,0,...,0,1,1,0,1,0,0,0,0,1
2,-8.380039e+06,4.862389e+06,3,2020067671,NaN,1,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
3,-8.375669e+06,4.857235e+06,4,2020086583,458.0,1,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
4,-8.378072e+06,4.848003e+06,5,2021029069,2355.0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0

In [43]:
with pd.option_context('display.max_rows', None):
    print(df.dtypes)

X                                 float64
Y                                 float64
objectid                            int64
crn                                 int64
arrival_tm                        float64
automobile_count                    int64
belted_death_count                  int64
belted_susp_serious_inj_count       int64
bicycle_count                       int64
bicycle_death_count                 int64
bicycle_susp_serious_inj_count      int64
bus_count                           int64
chldpas_death_count                 int64
chldpas_susp_serious_inj_count      int64
collision_type                      int64
comm_veh_count                      int64
cons_zone_spd_lim                 float64
county                              int64
crash_month                         int64
crash_year                          int64
day_of_week                         int64
dec_latitude                      float64
dec_longitude                     float64
dispatch_tm                       float64
district                            int64
driver_count_16yr                   int64
driver_count_17yr                   int64
driver_count_18yr                   int64
driver_count_19yr                   int64
driver_count_20yr                   int64
driver_count_50_64yr                int64
driver_count_65_74yr                int64
driver_count_75plus                 int64
est_hrs_closed                    float64
fatal_count                         int64
heavy_truck_count                   int64
horse_buggy_count                   int64
hour_of_day                       float64
illumination                      float64
injury_count                        int64
intersection_related_x                str
intersect_type                      int64
lane_closed                       float64
latitude                              str
ln_close_dir                      float64
location_type                       int64
longitude                             str
max_severity_level                  int64
mcycle_death_count                  int64
mcycle_susp_serious_inj_count       int64
motorcycle_count                    int64
municipality                        int64
nonmotr_count                       int64
nonmotr_death_count                 int64
nonmotr_susp_serious_inj_count      int64
ntfy_hiwy_maint                       str
ped_count                           int64
ped_death_count                     int64
ped_susp_serious_inj_count          int64
person_count                        int64
police_agcy                           str
possible_inj_count                  int64
rdwy_surf_type_cd                 float64
relation_to_road                    int64
roadway_cleared                   float64
road_condition                      int64
sch_bus_ind                           str
sch_zone_ind                          str
secondary_crash                       str
small_truck_count                   int64
spec_juris_cd                     float64
susp_minor_inj_count                int64
susp_serious_inj_count              int64
suv_count                           int64
tcd_func_cd                       float64
tcd_type                            int64
tfc_detour_ind                        str
time_of_day                       float64
total_units                         int64
tot_inj_count                       int64
unbelted_occ_count                  int64
unb_death_count                     int64
unb_susp_serious_inj_count          int64
unk_inj_deg_count                   int64
unk_inj_per_count                   int64
urban_rural                         int64
van_count                           int64
vehicle_count                       int64
weather1                          float64
weather2                          float64
workers_pres                          str
work_zone_ind                         str
work_zone_loc                     float64
work_zone_type                    float64
wz_close_detour                       str
wz_flagger                            str
wz_law_offcr_ind                      str
wz_ln_closure                         str
wz_moving                             str
wz_other                              str
wz_shlder_mdn                         str
wz_workers_inj_killed                 str
aggressive_driving                  int64
alcohol_related                     int64
angle_crash                         int64
atv                                 int64
atv_route                           int64
backup_congestion                   int64
backup_nonrecurring                 int64
backup_prior                        int64
bicycle                             int64
cell_phone                          int64
child_passenger                     int64
comm_vehicle                        int64
core_network                        int64
cross_median                        int64
curved_road                         int64
curve_dvr_error                     int64
deer_related                        int64
distracted                          int64
drinking_driver                     int64
driver_16yr                         int64
driver_17yr                         int64
driver_18yr                         int64
driver_19yr                         int64
driver_20yr                         int64
driver_50_64yr                      int64
driver_65_74yr                      int64
driver_75plus                       int64
drugged_driver                      int64
drug_related                        int64
fatal                               int64
fatal_or_susp_serious_inj           int64
fatigue_asleep                      int64
federal_aid_route                   int64
fire_in_vehicle                     int64
hazardous_truck                     int64
hit_barrier                         int64
hit_bridge                          int64
hit_deer                            int64
hit_embankment                      int64
hit_fixed_object                    int64
hit_gdrail                          int64
hit_gdrail_end                      int64
hit_parked_vehicle                  int64
hit_pole                            int64
hit_roadway_equipment               int64
hit_run                             int64
hit_temp_construction_barrier       int64
hit_traffic_island                  int64
hit_tree_shrub                      int64
hit_utility_pole                    int64
horse_buggy                       float64
ho_oppdir_sdswp                     int64
hvy_truck_related                   int64
icy_road                            int64
illegal_drug_related                int64
illumination_dark                   int64
impaired_driver                     int64
impaired_nonmotorist                int64
injury                              int64
injury_or_fatal                     int64
intersection                        int64
intersection_related_y              int64
interstate                          int64
lane_departure                      int64
left_turn                           int64
limit_65mph                         int64
limit_70mph                       float64
local_road                          int64
local_road_only                     int64
marijuana_drugged_driver            int64
marijuana_related                   int64
mature_driver                       int64
mc_drinking_driver                  int64
motorcycle                          int64
multiple_vehicle                    int64
nhtsa_agg_driving                   int64
non_intersection                    int64
no_clearance                        int64
opioid_related                      int64
other_freeway_expressway            int64
overturned                          int64
pedestrian                          int64
phantom_vehicle                     int64
possible_injury                     int64
property_damage_only                int64
psp_reported                        int64
ramp                                int64
ramp_segment                        int64
ramp_terminal                       int64
rear_end                            int64
roundabout                          int64
running_red_lt                      int64
running_stop_sign                   int64
rural                               int64
school_bus                          int64
school_bus_related                  int64
school_bus_unit                     int64
school_zone                         int64
shldr_related                       int64
signalized_int                      int64
single_vehicle                      int64
snowmobile                          int64
snow_slush_road                     int64
speeding                            int64
speeding_related                    int64
speed_change_lane                   int64
state_road                          int64
stop_controlled_int                 int64
sudden_deer                         int64
suspected_minor_injury              int64
suspected_serious_injury            int64
sv_run_off_rd                       int64
tailgating                          int64
train                               int64
train_trolley                       int64
trolley                             int64
turnpike                            int64
unbelted                            int64
underage_drnk_drv                   int64
unlicensed                          int64
unsignalized_int                    int64
urban                               int64
vehicle_failure                     int64
vehicle_towed                       int64
vulnerable_road_user                int64
vulnerable_road_user_fatal          int64
wet_road                            int64
work_zone                           int64
young_driver                        int64
dtype: object

In [44]:
with pd.option_context('display.max_rows', None):
    print(df.isnull().sum())

X                                     0
Y                                     0
objectid                              0
crn                                   0
arrival_tm                        10019
automobile_count                      0
belted_death_count                    0
belted_susp_serious_inj_count         0
bicycle_count                         0
bicycle_death_count                   0
bicycle_susp_serious_inj_count        0
bus_count                             0
chldpas_death_count                   0
chldpas_susp_serious_inj_count        0
collision_type                        0
comm_veh_count                        0
cons_zone_spd_lim                 36199
county                                0
crash_month                           0
crash_year                            0
day_of_week                           0
dec_latitude                          0
dec_longitude                         0
dispatch_tm                        8998
district                              0
driver_count_16yr                     0
driver_count_17yr                     0
driver_count_18yr                     0
driver_count_19yr                     0
driver_count_20yr                     0
driver_count_50_64yr                  0
driver_count_65_74yr                  0
driver_count_75plus                   0
est_hrs_closed                    36292
fatal_count                           0
heavy_truck_count                     0
horse_buggy_count                     0
hour_of_day                       34341
illumination                      36303
injury_count                          0
intersection_related_x            21012
intersect_type                        0
lane_closed                       36303
latitude                              0
ln_close_dir                      28511
location_type                         0
longitude                             0
max_severity_level                    0
mcycle_death_count                    0
mcycle_susp_serious_inj_count         0
motorcycle_count                      0
municipality                          0
nonmotr_count                         0
nonmotr_death_count                   0
nonmotr_susp_serious_inj_count        0
ntfy_hiwy_maint                       0
ped_count                             0
ped_death_count                       0
ped_susp_serious_inj_count            0
person_count                          0
police_agcy                           0
possible_inj_count                    0
rdwy_surf_type_cd                 35683
relation_to_road                      0
roadway_cleared                   28511
road_condition                        0
sch_bus_ind                         791
sch_zone_ind                        800
secondary_crash                       0
small_truck_count                     0
spec_juris_cd                     35683
susp_minor_inj_count                  0
susp_serious_inj_count                0
suv_count                             0
tcd_func_cd                       32381
tcd_type                              0
tfc_detour_ind                    28299
time_of_day                       34341
total_units                           0
tot_inj_count                         0
unbelted_occ_count                    0
unb_death_count                       0
unb_susp_serious_inj_count            0
unk_inj_deg_count                     0
unk_inj_per_count                     0
urban_rural                           0
van_count                             0
vehicle_count                         0
weather1                          27719
weather2                          11345
workers_pres                      36199
work_zone_ind                         0
work_zone_loc                     36199
work_zone_type                    36199
wz_close_detour                   36227
wz_flagger                        36228
wz_law_offcr_ind                  36199
wz_ln_closure                     36214
wz_moving                         36230
wz_other                          36225
wz_shlder_mdn                     36224
wz_workers_inj_killed             36199
aggressive_driving                    0
alcohol_related                       0
angle_crash                           0
atv                                   0
atv_route                             0
backup_congestion                     0
backup_nonrecurring                   0
backup_prior                          0
bicycle                               0
cell_phone                            0
child_passenger                       0
comm_vehicle                          0
core_network                          0
cross_median                          0
curved_road                           0
curve_dvr_error                       0
deer_related                          0
distracted                            0
drinking_driver                       0
driver_16yr                           0
driver_17yr                           0
driver_18yr                           0
driver_19yr                           0
driver_20yr                           0
driver_50_64yr                        0
driver_65_74yr                        0
driver_75plus                         0
drugged_driver                        0
drug_related                          0
fatal                                 0
fatal_or_susp_serious_inj             0
fatigue_asleep                        0
federal_aid_route                     0
fire_in_vehicle                       0
hazardous_truck                       0
hit_barrier                           0
hit_bridge                            0
hit_deer                              0
hit_embankment                        0
hit_fixed_object                      0
hit_gdrail                            0
hit_gdrail_end                        0
hit_parked_vehicle                    0
hit_pole                              0
hit_roadway_equipment                 0
hit_run                               0
hit_temp_construction_barrier         0
hit_traffic_island                    0
hit_tree_shrub                        0
hit_utility_pole                      0
horse_buggy                          26
ho_oppdir_sdswp                       0
hvy_truck_related                     0
icy_road                              0
illegal_drug_related                  0
illumination_dark                     0
impaired_driver                       0
impaired_nonmotorist                  0
injury                                0
injury_or_fatal                       0
intersection                          0
intersection_related_y                0
interstate                            0
lane_departure                        0
left_turn                             0
limit_65mph                           0
limit_70mph                           4
local_road                            0
local_road_only                       0
marijuana_drugged_driver              0
marijuana_related                     0
mature_driver                         0
mc_drinking_driver                    0
motorcycle                            0
multiple_vehicle                      0
nhtsa_agg_driving                     0
non_intersection                      0
no_clearance                          0
opioid_related                        0
other_freeway_expressway              0
overturned                            0
pedestrian                            0
phantom_vehicle                       0
possible_injury                       0
property_damage_only                  0
psp_reported                          0
ramp                                  0
ramp_segment                          0
ramp_terminal                         0
rear_end                              0
roundabout                            0
running_red_lt                        0
running_stop_sign                     0
rural                                 0
school_bus                            0
school_bus_related                    0
school_bus_unit                       0
school_zone                           0
shldr_related                         0
signalized_int                        0
single_vehicle                        0
snowmobile                            0
snow_slush_road                       0
speeding                              0
speeding_related                      0
speed_change_lane                     0
state_road                            0
stop_controlled_int                   0
sudden_deer                           0
suspected_minor_injury                0
suspected_serious_injury              0
sv_run_off_rd                         0
tailgating                            0
train                                 0
train_trolley                         0
trolley                               0
turnpike                              0
unbelted                              0
underage_drnk_drv                     0
unlicensed                            0
unsignalized_int                      0
urban                                 0
vehicle_failure                       0
vehicle_towed                         0
vulnerable_road_user                  0
vulnerable_road_user_fatal            0
wet_road                              0
work_zone                             0
young_driver                          0
dtype: int64

In [45]:
df.head(10)

,X,Y,objectid,crn,arrival_tm,automobile_count,belted_death_count,belted_susp_serious_inj_count,bicycle_count,bicycle_death_count,...,unlicensed,unsignalized_int,urban,vehicle_failure,vehicle_towed,vulnerable_road_user,vulnerable_road_user_fatal,wet_road,work_zone,young_driver
0,-8.376536e+06,4.860532e+06,1,2020007295,NaN,4,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
1,-8.379867e+06,4.862518e+06,2,2020066105,1742.0,1,0,0,0,0,...,0,1,1,0,1,0,0,0,0,1
2,-8.380039e+06,4.862389e+06,3,2020067671,NaN,1,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
3,-8.375669e+06,4.857235e+06,4,2020086583,458.0,1,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
4,-8.378072e+06,4.848003e+06,5,2021029069,2355.0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
5,-8.376589e+06,4.859744e+06,6,2021043799,1341.0,0,0,1,0,0,...,0,1,1,0,1,0,0,0,0,0
6,-8.376534e+06,4.860532e+06,7,2021104405,159.0,2,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
7,-8.372787e+06,4.848033e+06,8,2022037781,2158.0,1,0,0,0,0,...,0,0,1,0,1,0,0,0,0,1
8,-8.379866e+06,4.862507e+06,9,2022075157,1409.0,2,0,0,0,0,...,0,1,1,1,1,0,0,0,0,0
9,-8.375824e+06,4.848980e+06,10,2022113691,1550.0,1,0,0,0,0,...,0,1,1,0,1,0,0,0,0,0

In [46]:
df.columns = (
    df.columns
    .str.replace(' ', '_')
    .str.lower()
    .str.strip()
)

In [47]:
missing = df.isnull().mean() * 100
print(missing[missing > 0].sort_values(ascending= False))

lane_closed               100.000000
illumination              100.000000
est_hrs_closed             99.969699
wz_moving                  99.798915
wz_flagger                 99.793406
wz_close_detour            99.790651
wz_other                   99.785142
wz_shlder_mdn              99.782387
wz_ln_closure              99.754841
workers_pres               99.713522
work_zone_type             99.713522
cons_zone_spd_lim          99.713522
wz_workers_inj_killed      99.713522
work_zone_loc              99.713522
wz_law_offcr_ind           99.713522
spec_juris_cd              98.292152
rdwy_surf_type_cd          98.292152
hour_of_day                94.595488
time_of_day                94.595488
tcd_func_cd                89.196485
ln_close_dir               78.536209
roadway_cleared            78.536209
tfc_detour_ind             77.952235
weather1                   76.354571
intersection_related_x     57.879514
weather2                   31.250861
arrival_tm                 27.598270
dispatch_tm                24.785830
sch_zone_ind                2.203675
sch_bus_ind                 2.178883
horse_buggy                 0.071619
limit_70mph                 0.011018
dtype: float64

In [48]:
n_dupes = df.duplicated().sum()
n_dupes

np.int64(0)

In [49]:
df[df.duplicated(keep = False)].sort_values(by = list(df.columns)).head(10)

Empty DataFrame
Columns: [x, y, objectid, crn, arrival_tm, automobile_count, belted_death_count, belted_susp_serious_inj_count, bicycle_count, bicycle_death_count, bicycle_susp_serious_inj_count, bus_count, chldpas_death_count, chldpas_susp_serious_inj_count, collision_type, comm_veh_count, cons_zone_spd_lim, county, crash_month, crash_year, day_of_week, dec_latitude, dec_longitude, dispatch_tm, district, driver_count_16yr, driver_count_17yr, driver_count_18yr, driver_count_19yr, driver_count_20yr, driver_count_50_64yr, driver_count_65_74yr, driver_count_75plus, est_hrs_closed, fatal_count, heavy_truck_count, horse_buggy_count, hour_of_day, illumination, injury_count, intersection_related_x, intersect_type, lane_closed, latitude, ln_close_dir, location_type, longitude, max_severity_level, mcycle_death_count, mcycle_susp_serious_inj_count, motorcycle_count, municipality, nonmotr_count, nonmotr_death_count, nonmotr_susp_serious_inj_count, ntfy_hiwy_maint, ped_count, ped_death_count, ped_susp_serious_inj_count, person_count, police_agcy, possible_inj_count, rdwy_surf_type_cd, relation_to_road, roadway_cleared, road_condition, sch_bus_ind, sch_zone_ind, secondary_crash, small_truck_count, spec_juris_cd, susp_minor_inj_count, susp_serious_inj_count, suv_count, tcd_func_cd, tcd_type, tfc_detour_ind, time_of_day, total_units, tot_inj_count, unbelted_occ_count, unb_death_count, unb_susp_serious_inj_count, unk_inj_deg_count, unk_inj_per_count, urban_rural, van_count, vehicle_count, weather1, weather2, workers_pres, work_zone_ind, work_zone_loc, work_zone_type, wz_close_detour, wz_flagger, wz_law_offcr_ind, wz_ln_closure, wz_moving, wz_other, ...]
Index: []

[0 rows x 231 columns]

In [50]:
df = df.drop_duplicates()

In [51]:
df.shape

(36303, 231)