# DAAN 545 Group 1: Group Project PennDOT Crash Data Statewide 2020-2024

In [ ]:
import pandas as pd

# 1. Load Crash and Flag tables for years 2020-2024

# 2024
crash_2024 = pd.read_csv("Data\\Crash_2024.csv", dtype={"CRN": str})
flags_2024 = pd.read_csv("Data\\Flags_2024.csv", dtype={"CRN": str})

# 2023
crash_2023 = pd.read_csv("Data\\Crash_2023.csv", dtype={"CRN": str})
flags_2023 = pd.read_csv("Data\\Flags_2023.csv", dtype={"CRN": str})

# 2022
crash_2022 = pd.read_csv("Data\\Crash_2022.csv", dtype={"CRN": str})
flags_2022 = pd.read_csv("Data\\Flags_2022.csv", dtype={"CRN": str})

# 2021
crash_2021 = pd.read_csv("Data\\Crash_2021.csv", dtype={"CRN": str})
flags_2021 = pd.read_csv("Data\\Flags_2021.csv", dtype={"CRN": str})

# 2020
crash_2020 = pd.read_csv("Data\\Crash_2020.csv", dtype={"CRN": str})
flags_2020 = pd.read_csv("Data\\Flags_2020.csv", dtype={"CRN": str})

In [ ]:
# Union the years 2020-2024 using pd.concat

crash = pd.concat([crash_2020, crash_2021, crash_2022, crash_2023, crash_2024], ignore_index=True).drop_duplicates()
flags = pd.concat([flags_2020, flags_2021, flags_2022, flags_2023, flags_2024], ignore_index=True).drop_duplicates()

In [ ]:
# Standardize column names

crash.columns = crash.columns.str.upper().str.strip()
flags.columns = flags.columns.str.upper().str.strip()

In [ ]:
# Merge Crash and Flag

merged_df = crash.merge(flags, on="CRN", how="left")

In [72]:
# Check shape and size

print(f'Shape: {merged_df.shape}')
print(f'Size: {merged_df.size}')

Shape: (560396, 228)
Size: 127770288

In [73]:
# Checking missing values

missing = (
    merged_df.isna()
    .mean()
    .sort_values(ascending=False)
    .to_frame("missing_pct")
)
missing.query('missing_pct > 0.90')

                       missing_pct
ILLUMINATION              1.000000
LANE_CLOSED               1.000000
EST_HRS_CLOSED            0.999656
WZ_CLOSE_DETOUR           0.994875
WZ_FLAGGER                0.994727
WZ_MOVING                 0.994620
WZ_OTHER                  0.994101
WZ_SHLDER_MDN             0.992641
WZ_LN_CLOSURE             0.992598
RDWY_SURF_TYPE_CD         0.990196
SPEC_JURIS_CD             0.990196
WZ_WORKERS_INJ_KILLED     0.988813
WORK_ZONE_LOC             0.988776
WORKERS_PRES              0.988776
WORK_ZONE_TYPE            0.988776
WZ_LAW_OFFCR_IND          0.988776
CONS_ZONE_SPD_LIM         0.988776
TIME_OF_DAY               0.948858
HOUR_OF_DAY               0.948858
TCD_FUNC_CD               0.912444

In [74]:
with pd.option_context('display.max_columns', None):
    display(merged_df.head())

,CRN,ARRIVAL_TM,AUTOMOBILE_COUNT,BELTED_DEATH_COUNT,BELTED_SUSP_SERIOUS_INJ_COUNT,BICYCLE_COUNT,BICYCLE_DEATH_COUNT,BICYCLE_SUSP_SERIOUS_INJ_COUNT,BUS_COUNT,CHLDPAS_DEATH_COUNT,CHLDPAS_SUSP_SERIOUS_INJ_COUNT,COLLISION_TYPE,COMM_VEH_COUNT,CONS_ZONE_SPD_LIM,COUNTY,CRASH_MONTH,CRASH_YEAR,DAY_OF_WEEK,DEC_LATITUDE,DEC_LONGITUDE,DISPATCH_TM,DISTRICT,DRIVER_COUNT_16YR,DRIVER_COUNT_17YR,DRIVER_COUNT_18YR,DRIVER_COUNT_19YR,DRIVER_COUNT_20YR,DRIVER_COUNT_50_64YR,DRIVER_COUNT_65_74YR,DRIVER_COUNT_75PLUS,EST_HRS_CLOSED,FATAL_COUNT,HEAVY_TRUCK_COUNT,HORSE_BUGGY_COUNT,HOUR_OF_DAY,ILLUMINATION,INJURY_COUNT,INTERSECTION_RELATED_x,INTERSECT_TYPE,LANE_CLOSED,LATITUDE,LN_CLOSE_DIR,LOCATION_TYPE,LONGITUDE,MAX_SEVERITY_LEVEL,MCYCLE_DEATH_COUNT,MCYCLE_SUSP_SERIOUS_INJ_COUNT,MOTORCYCLE_COUNT,MUNICIPALITY,NONMOTR_COUNT,NONMOTR_DEATH_COUNT,NONMOTR_SUSP_SERIOUS_INJ_COUNT,NTFY_HIWY_MAINT,PED_COUNT,PED_DEATH_COUNT,PED_SUSP_SERIOUS_INJ_COUNT,PERSON_COUNT,POLICE_AGCY,POSSIBLE_INJ_COUNT,RDWY_SURF_TYPE_CD,RELATION_TO_ROAD,ROADWAY_CLEARED,ROAD_CONDITION,SCH_BUS_IND,SCH_ZONE_IND,SECONDARY_CRASH,SMALL_TRUCK_COUNT,SPEC_JURIS_CD,SUSP_MINOR_INJ_COUNT,SUSP_SERIOUS_INJ_COUNT,SUV_COUNT,TCD_FUNC_CD,TCD_TYPE,TFC_DETOUR_IND,TIME_OF_DAY,TOTAL_UNITS,TOT_INJ_COUNT,UNBELTED_OCC_COUNT,UNB_DEATH_COUNT,UNB_SUSP_SERIOUS_INJ_COUNT,UNK_INJ_DEG_COUNT,UNK_INJ_PER_COUNT,URBAN_RURAL,VAN_COUNT,VEHICLE_COUNT,WEATHER1,WEATHER2,WORKERS_PRES,WORK_ZONE_IND,WORK_ZONE_LOC,WORK_ZONE_TYPE,WZ_CLOSE_DETOUR,WZ_FLAGGER,WZ_LAW_OFFCR_IND,WZ_LN_CLOSURE,WZ_MOVING,WZ_OTHER,WZ_SHLDER_MDN,WZ_WORKERS_INJ_KILLED,AGGRESSIVE_DRIVING,ALCOHOL_RELATED,ANGLE_CRASH,ATV,ATV_ROUTE,BACKUP_CONGESTION,BACKUP_NONRECURRING,BACKUP_PRIOR,BICYCLE,CELL_PHONE,CHILD_PASSENGER,COMM_VEHICLE,CORE_NETWORK,CROSS_MEDIAN,CURVED_ROAD,CURVE_DVR_ERROR,DEER_RELATED,DISTRACTED,DRINKING_DRIVER,DRIVER_16YR,DRIVER_17YR,DRIVER_18YR,DRIVER_19YR,DRIVER_20YR,DRIVER_50_64YR,DRIVER_65_74YR,DRIVER_75PLUS,DRUGGED_DRIVER,DRUG_RELATED,FATAL,FATAL_OR_SUSP_SERIOUS_INJ,FATIGUE_ASLEEP,FEDERAL_AID_ROUTE,FIRE_IN_VEHICLE,HAZARDOUS_TRUCK,HIT_BARRIER,HIT_BRIDGE,HIT_DEER,HIT_EMBANKMENT,HIT_FIXED_OBJECT,HIT_GDRAIL,HIT_GDRAIL_END,HIT_PARKED_VEHICLE,HIT_POLE,HIT_ROADWAY_EQUIPMENT,HIT_RUN,HIT_TEMP_CONSTRUCTION_BARRIER,HIT_TRAFFIC_ISLAND,HIT_TREE_SHRUB,HIT_UTILITY_POLE,HORSE_BUGGY,HO_OPPDIR_SDSWP,HVY_TRUCK_RELATED,ICY_ROAD,ILLEGAL_DRUG_RELATED,ILLUMINATION_DARK,IMPAIRED_DRIVER,IMPAIRED_NONMOTORIST,INJURY,INJURY_OR_FATAL,INTERSECTION,INTERSECTION_RELATED_y,INTERSTATE,LANE_DEPARTURE,LEFT_TURN,LIMIT_65MPH,LIMIT_70MPH,LOCAL_ROAD,LOCAL_ROAD_ONLY,MARIJUANA_DRUGGED_DRIVER,MARIJUANA_RELATED,MATURE_DRIVER,MC_DRINKING_DRIVER,MOTORCYCLE,MULTIPLE_VEHICLE,NHTSA_AGG_DRIVING,NON_INTERSECTION,NO_CLEARANCE,OPIOID_RELATED,OTHER_FREEWAY_EXPRESSWAY,OVERTURNED,PEDESTRIAN,PHANTOM_VEHICLE,POSSIBLE_INJURY,PROPERTY_DAMAGE_ONLY,PSP_REPORTED,RAMP,RAMP_SEGMENT,RAMP_TERMINAL,REAR_END,ROUNDABOUT,RUNNING_RED_LT,RUNNING_STOP_SIGN,RURAL,SCHOOL_BUS,SCHOOL_BUS_RELATED,SCHOOL_BUS_UNIT,SCHOOL_ZONE,SHLDR_RELATED,SIGNALIZED_INT,SINGLE_VEHICLE,SNOWMOBILE,SNOW_SLUSH_ROAD,SPEEDING,SPEEDING_RELATED,SPEED_CHANGE_LANE,STATE_ROAD,STOP_CONTROLLED_INT,SUDDEN_DEER,SUSPECTED_MINOR_INJURY,SUSPECTED_SERIOUS_INJURY,SV_RUN_OFF_RD,TAILGATING,TRAIN,TRAIN_TROLLEY,TROLLEY,TURNPIKE,UNBELTED,UNDERAGE_DRNK_DRV,UNLICENSED,UNSIGNALIZED_INT,URBAN,VEHICLE_FAILURE,VEHICLE_TOWED,VULNERABLE_ROAD_USER,VULNERABLE_ROAD_USER_FATAL,WET_ROAD,WORK_ZONE,YOUNG_DRIVER
0,2019133973,NaN,2,0,0,0,0,0,0,0,0,4,0,NaN,41,5,2020,7,41.251664,-77.047469,NaN,3,0,0,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1,N,1,NaN,41 15:05.990,1.0,0,77 02:50.890,4,0,0,0,41230,0,0,0,N,0,0,0,6,41230,1,NaN,1.0,30.0,1,N,N,N,1,NaN,0,0,0,NaN,0,N,NaN,3,1,0,0,0,0,0,2,0,3,NaN,3.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,1,1,1,0,0,0,1,0,0.0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0
1,2020006647,1511.0,1,0,0,0,0,0,0,0,0,7,0,NaN,46,1,2020,7,40.254116,-75.304833,1511.0,6,0,0,0,0,1,0,0,0,NaN,0,0,0,NaN,NaN,0,NaN,1,NaN,40 15:14.819,NaN,0,75 18:17.399,0,0,0,0,46216,0,0,0,N,0,0,0,2,46216,0,NaN,5.0,NaN,7,N,N,N,0,NaN,0,0,0,NaN,2,N,NaN,1,0,0,0,0,0,0,2,0,1,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0.0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1
2,2020024016,638.0,1,0,0,0,0,0,0,0,0,7,0,NaN,39,2,2020,6,40.628493,-75.392806,632.0,5,0,0,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,1,NaN,6,NaN,40 37:42.573,NaN,2,75 23:34.103,3,0,0,0,39302,0,0,0,N,0,0,0,1,48301,0,NaN,4.0,NaN,9,N,N,N,0,NaN,1,0,0,NaN,0,NaN,NaN,1,1,1,0,0,0,0,2,0,1,NaN,4.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,1,0,0
3,2020029257,1957.0,1,0,0,0,0,0,0,0,0,2,0,NaN,67,3,2020,3,39.994631,-75.094531,1948.0,6,0,0,0,0,0,0,0,0,NaN,0,0,0,NaN,NaN,4,NaN,1,NaN,39 59:40.673,NaN,0,75 05:40.311,4,0,0,0,67301,0,0,0,N,0,0,0,5,67301,4,NaN,1.0,NaN,1,N,N,N,0,NaN,0,0,1,NaN,2,NaN,NaN,2,4,3,0,0,0,1,2,0,2,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0.0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0
4,2020008250,1950.0,1,0,0,0,0,0,0,0,0,7,0,NaN,2,1,2020,3,40.433163,-80.210593,1948.0,11,0,0,0,0,0,1,0,0,NaN,0,0,0,NaN,NaN,1,NaN,2,NaN,40 25:59.386,NaN,0,80 12:38.134,4,0,0,0,2214,0,0,0,N,0,0,0,1,02214,1,NaN,5.0,NaN,1,N,N,N,0,NaN,0,0,0,NaN,0,NaN,NaN,1,1,0,0,0,0,0,2,0,1,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,1,1,0,1,1,1,0,0,0,0,0,0.0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0